plugins {
    alias(libs.plugins.android.asset.pack)
}

// Fast-follow pack: Play downloads it in the background right after install (spec section 11).
// Clips are generated by content/pipeline/tts.py into src/main/assets/audio/.
assetPack {
    packName.set("audio_pack")
    dynamicDelivery {
        deliveryType.set("fast-follow")
    }
}
